name: Export, Zip, and Release

on:
  push:
    tags:
      - 'v-*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Godot Export
        id: godotExport
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.3/mono/Godot_v4.3-stable_mono_linux_x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.3/mono/Godot_v4.3-stable_mono_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          # cache: true

      # - name: List Archive Directory Contents
      #   run: ls -la ${{ steps.godotExport.outputs.archive_directory }}
        

      # - name: release
      #   uses: ncipollo/release-action@v1.14.0
      #   with:
      #     token: ${{ secrets.GH_TOKEN }}
      #     tag: ${{ github.ref_name }}
      #     artifacts: ${{ steps.godotExport.outputs.archive_directory }}/block-breaker-win-64.zip
      #     generateReleaseNotes: true
          

      - name: Publish to Itch
        uses: Ayowel/butler-to-itch@v1.0.0
        with:
          butler_key: ${{secrets.ITCHIO_API_KEY}}
          itch_user: shaikh-yakub-hossain
          itch_game: block-breaker
          version: ${{ github.ref_name }}
          files: ${{ steps.godotExport.outputs.archive_directory }}//block-breaker-win-64.zip
    